const shoppingList = [
    {
        id: 'il01',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new1.jpg',
    },
    {
        id: 'il02',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/new2.jpg',
    },
    {
        id: 'il03',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/new3.jpg',
    },
    {
        id: 'il04',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/new4.jpg',
    },
    {
        id: 'il05',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new5.jpg',
    },
    {
        id: 'il06',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/new6.jpg',
    },
    {
        id: 'il07',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/new7.jpg',
    },
    {
        id: 'il08',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/new8.jpg',
    },
    {
        id: 'il09',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new9.jpg',
    },
    {
        id: 'il10',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/best1.jpg',
    },
    {
        id: 'il11',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/best2.jpg',
    },
    {
        id: 'il12',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/best3.jpg',
    },
    {
        id: 'il13',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/best4.jpg',
    },
    {
        id: 'il14',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/best5.jpg',
    },
    {
        id: 'il15',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/best6.jpg',
    },
    {
        id: 'il16',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/best7.jpg',
    },
    {
        id: 'il01',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/table1.jpg',
    },
    {
        id: 'il02',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/table2.jpg',
    },
    {
        id: 'il03',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/table3.jpg',
    },
    {
        id: 'il04',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/table4.jpg',
    },
    {
        id: 'il05',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/table5.jpg',
    },
    {
        id: 'il06',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/table6.jpg',
    },
    {
        id: 'il07',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/living3.jpg',
    },
    {
        id: 'il08',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/living4.jpg',
    },
    {
        id: 'il09',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/living5.jpg',
    },
    {
        id: 'il10',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/living6.jpg',
    },
    {
        id: 'il11',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/dinig1.jpg',
    },
    {
        id: 'il12',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/dinig2.jpg',
    },
    {
        id: 'il13',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/dinig3.jpg',
    },
    {
        id: 'il14',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/dinig4.jpg',
    },
    {
        id: 'il15',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/dinig5.jpg',
    },
    {
        id: 'il16',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/dinig6.jpg',
    },
    {
        id: 'il01',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new1.jpg',
    },
    {
        id: 'il02',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/new2.jpg',
    },
    {
        id: 'il03',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/new3.jpg',
    },
    {
        id: 'il04',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/new4.jpg',
    },
    {
        id: 'il05',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new5.jpg',
    },
    {
        id: 'il06',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/new6.jpg',
    },
    {
        id: 'il07',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/new7.jpg',
    },
    {
        id: 'il08',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/new8.jpg',
    },
    {
        id: 'il09',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new9.jpg',
    },
    {
        id: 'il10',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/best1.jpg',
    },
    {
        id: 'il11',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/best2.jpg',
    },
    {
        id: 'il12',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/best3.jpg',
    },
    {
        id: 'il13',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/best4.jpg',
    },
    {
        id: 'il14',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/best5.jpg',
    },
    {
        id: 'il15',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/best6.jpg',
    },
    {
        id: 'il16',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/best7.jpg',
    },
    {
        id: 'il01',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/table1.jpg',
    },
    {
        id: 'il02',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/table2.jpg',
    },
    {
        id: 'il03',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/table3.jpg',
    },
    {
        id: 'il04',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/table4.jpg',
    },
    {
        id: 'il05',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/table5.jpg',
    },
    {
        id: 'il06',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/table6.jpg',
    },
    {
        id: 'il07',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/living3.jpg',
    },
    {
        id: 'il08',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/living4.jpg',
    },
    {
        id: 'il09',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/living5.jpg',
    },
    {
        id: 'il10',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/living6.jpg',
    },
    {
        id: 'il11',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/dinig1.jpg',
    },
    {
        id: 'il12',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/dinig2.jpg',
    },
    {
        id: 'il13',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/dinig3.jpg',
    },
    {
        id: 'il14',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/dinig4.jpg',
    },
    {
        id: 'il15',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/dinig5.jpg',
    },
    {
        id: 'il16',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/dinig6.jpg',
    },
    {
        id: 'il01',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new1.jpg',
    },
    {
        id: 'il02',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/new2.jpg',
    },
    {
        id: 'il03',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/new3.jpg',
    },
    {
        id: 'il04',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/new4.jpg',
    },
    {
        id: 'il05',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new5.jpg',
    },
    {
        id: 'il06',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/new6.jpg',
    },
    {
        id: 'il07',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/new7.jpg',
    },
    {
        id: 'il08',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/new8.jpg',
    },
    {
        id: 'il09',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/new9.jpg',
    },
    {
        id: 'il10',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/best1.jpg',
    },
    {
        id: 'il11',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/best2.jpg',
    },
    {
        id: 'il12',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/best3.jpg',
    },
    {
        id: 'il13',
        name: 'IK 테이블 스탠드 SNOWMAN15 Portable Stand',
        price: 110000,
        src: './images/best4.jpg',
    },
    {
        id: 'il14',
        name: 'IK 플로어 스탠드 SWAN2 Floor Stand',
        price: 340000,
        src: './images/best5.jpg',
    },
    {
        id: 'il15',
        name: 'IK 테이블 스탠드 SWAN2 Table Stand',
        price: 240000,
        src: './images/best6.jpg',
    },
    {
        id: 'il16',
        name: 'IK 팬던트 PINOCCHIO120 A Pendant',
        price: 110000,
        src: './images/best7.jpg',
    },
];

export default shoppingList; //exprot로 내보내지 않으면 import로 가져올 수 없다
